--------------------------------------------------------
--  File created - Tuesday-January-01-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ART
--------------------------------------------------------

  CREATE TABLE "DALI"."ART" 
   (	"ARTID" VARCHAR2(10 BYTE), 
	"URL" VARCHAR2(10 BYTE), 
	"ARTISTID" VARCHAR2(10 BYTE), 
	"TAGS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARTIST
--------------------------------------------------------

  CREATE TABLE "DALI"."ARTIST" 
   (	"ARTISTID" VARCHAR2(10 BYTE), 
	"PASS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GENERESFORCE
--------------------------------------------------------

  CREATE TABLE "DALI"."GENERESFORCE" 
   (	"GENERE" VARCHAR2(30 BYTE), 
	"ABSTRACTART" NUMBER(10,0), 
	"ABSTRACTEXPRESSIONISM" NUMBER(10,0), 
	"ARTLANGUAGE" NUMBER(10,0), 
	"ARTPHOTOGRAPHY" NUMBER(10,0), 
	"CARTOON" NUMBER(10,0), 
	"POLITICS" NUMBER(10,0), 
	"GRAFFITY" NUMBER(10,0), 
	"CHINESEABSTRACTPAINTING" NUMBER(10,0), 
	"COLORFIELD" NUMBER(10,0), 
	"CONCEPTUALART" NUMBER(10,0), 
	"CONSTRUCTIVISM" NUMBER(10,0), 
	"CUBISM" NUMBER(10,0), 
	"CYBERNETICART" NUMBER(10,0), 
	"DADA" NUMBER(10,0), 
	"DESTIJL" NUMBER(10,0), 
	"NEOPLASTICISM" NUMBER(10,0), 
	"EXPRESSIONISM" NUMBER(10,0), 
	"FOLKART" NUMBER(10,0), 
	"FLUXUS" NUMBER(10,0), 
	"FUTURISM" NUMBER(10,0), 
	"GRAFFITI" NUMBER(10,0), 
	"IMPRESSIONISM" NUMBER(10,0), 
	"KINETICART" NUMBER(10,0), 
	"LANDART" NUMBER(10,0), 
	"MANNERISM" NUMBER(10,0), 
	"MINIMALISM" NUMBER(10,0), 
	"POPART" NUMBER(10,0), 
	"ROMANTICISM" NUMBER(10,0), 
	"SUPREMATISM" NUMBER(10,0), 
	"SURREALISM" NUMBER(10,0), 
	"SYMBOLISM" NUMBER(10,0), 
	"VIDEOART" NUMBER(10,0), 
	"OTHER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DALI"."USERS" 
   (	"USERID" VARCHAR2(10 BYTE), 
	"PASS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERTOGENRE
--------------------------------------------------------

  CREATE TABLE "DALI"."USERTOGENRE" 
   (	"USERNAME" VARCHAR2(10 BYTE), 
	"ABSTRACTART" NUMBER(10,0), 
	"ABSTRACTEXPRESSIONISM" NUMBER(10,0), 
	"ARTLANGUAGE" NUMBER(10,0), 
	"ARTPHOTOGRAPHY" NUMBER(10,0), 
	"CARTOON" NUMBER(10,0), 
	"POLITICS" NUMBER(10,0), 
	"CHINESEABSTRACTPAINTING" NUMBER(10,0), 
	"COLORFIELD" NUMBER(10,0), 
	"CONCEPTUALART" NUMBER(10,0), 
	"CONSTRUCTIVISM" NUMBER(10,0), 
	"CUBISM" NUMBER(10,0), 
	"CYBERNETICART" NUMBER(10,0), 
	"DADA" NUMBER(10,0), 
	"DESTIJL" NUMBER(10,0), 
	"NEOPLASTICISM" NUMBER(10,0), 
	"EXPRESSIONISM" NUMBER(10,0), 
	"FOLKART" NUMBER(10,0), 
	"FLUXUS" NUMBER(10,0), 
	"FUTURISM" NUMBER(10,0), 
	"GRAFFITI" NUMBER(10,0), 
	"IMPRESSIONISM" NUMBER(10,0), 
	"KINETICART" NUMBER(10,0), 
	"LANDART" NUMBER(10,0), 
	"MANNERISM" NUMBER(10,0), 
	"MINIMALISM" NUMBER(10,0), 
	"POPART" NUMBER(10,0), 
	"ROMANTICISM" NUMBER(10,0), 
	"SUPREMATISM" NUMBER(10,0), 
	"SURREALISM" NUMBER(10,0), 
	"SYMBOLISM" NUMBER(10,0), 
	"VIDEOART" NUMBER(10,0), 
	"OTHER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DALI.ART
SET DEFINE OFF;
REM INSERTING into DALI.ARTIST
SET DEFINE OFF;
REM INSERTING into DALI.GENERESFORCE
SET DEFINE OFF;
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('AbstractArt',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('AbstractExpressionism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('ArtLanguage',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('ArtPhotography',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Cartoon',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Politics',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Graffity',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('ChineseAbstractPainting',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('ColorField',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('ConceptualArt',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Constructivism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Cubism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('CyberneticArt',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Dada',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('DeStijl',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Neoplasticism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Expressionism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('FolkArt',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Fluxus',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Futurism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Graffiti',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Impressionism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('KineticArt',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('LandArt',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Mannerism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Minimalism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('PopArt',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Romanticism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Suprematism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Surrealism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Surrealism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Symbolism',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('VideoArt',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into DALI.GENERESFORCE (GENERE,ABSTRACTART,ABSTRACTEXPRESSIONISM,ARTLANGUAGE,ARTPHOTOGRAPHY,CARTOON,POLITICS,GRAFFITY,CHINESEABSTRACTPAINTING,COLORFIELD,CONCEPTUALART,CONSTRUCTIVISM,CUBISM,CYBERNETICART,DADA,DESTIJL,NEOPLASTICISM,EXPRESSIONISM,FOLKART,FLUXUS,FUTURISM,GRAFFITI,IMPRESSIONISM,KINETICART,LANDART,MANNERISM,MINIMALISM,POPART,ROMANTICISM,SUPREMATISM,SURREALISM,SYMBOLISM,VIDEOART,OTHER) values ('Other',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
REM INSERTING into DALI.USERS
SET DEFINE OFF;
REM INSERTING into DALI.USERTOGENRE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ARTIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DALI"."ARTIST_PK" ON "DALI"."ARTIST" ("ARTISTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERTOGENRE
--------------------------------------------------------

  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("OTHER" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("VIDEOART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("SYMBOLISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("SURREALISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("SUPREMATISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("ROMANTICISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("POPART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("MINIMALISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("MANNERISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("LANDART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("KINETICART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("IMPRESSIONISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("GRAFFITI" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("FUTURISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("FLUXUS" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("FOLKART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("EXPRESSIONISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("NEOPLASTICISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("DESTIJL" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("DADA" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("CYBERNETICART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("CUBISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("CONSTRUCTIVISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("CONCEPTUALART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("COLORFIELD" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("CHINESEABSTRACTPAINTING" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("POLITICS" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("CARTOON" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("ARTPHOTOGRAPHY" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("ARTLANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("ABSTRACTEXPRESSIONISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("ABSTRACTART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERTOGENRE" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARTIST
--------------------------------------------------------

  ALTER TABLE "DALI"."ARTIST" ADD CONSTRAINT "ARTIST_PK" PRIMARY KEY ("ARTISTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DALI"."ARTIST" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "DALI"."ARTIST" MODIFY ("ARTISTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DALI"."USERS" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "DALI"."USERS" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ART
--------------------------------------------------------

  ALTER TABLE "DALI"."ART" MODIFY ("ARTISTID" NOT NULL ENABLE);
  ALTER TABLE "DALI"."ART" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "DALI"."ART" MODIFY ("ARTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GENERESFORCE
--------------------------------------------------------

  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("OTHER" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("VIDEOART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("SYMBOLISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("SURREALISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("SUPREMATISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("ROMANTICISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("POPART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("MINIMALISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("MANNERISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("LANDART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("KINETICART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("IMPRESSIONISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("GRAFFITI" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("FUTURISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("FLUXUS" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("FOLKART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("EXPRESSIONISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("NEOPLASTICISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("DESTIJL" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("DADA" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("CYBERNETICART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("CUBISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("CONSTRUCTIVISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("CONCEPTUALART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("COLORFIELD" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("CHINESEABSTRACTPAINTING" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("GRAFFITY" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("POLITICS" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("CARTOON" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("ARTPHOTOGRAPHY" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("ARTLANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("ABSTRACTEXPRESSIONISM" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("ABSTRACTART" NOT NULL ENABLE);
  ALTER TABLE "DALI"."GENERESFORCE" MODIFY ("GENERE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ART
--------------------------------------------------------

  ALTER TABLE "DALI"."ART" ADD CONSTRAINT "ARTISTID_FK" FOREIGN KEY ("ARTISTID")
	  REFERENCES "DALI"."ARTIST" ("ARTISTID") ENABLE;
